name: Build e Geracao de APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Encontrar pasta e compilar web
        run: |
          # Localiza automaticamente a pasta onde está o package.json
          TARGET_DIR=$(find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \;)
          echo "Pasta do projeto encontrada: $TARGET_DIR"
          cd "$TARGET_DIR"
          
          # Instala dependencias e compila
          npm install
          npm run build || npm run generate || true

      - name: Salvar arquivos da WEB compilada (dist)
        uses: actions/upload-artifact@v4
        with:
          name: site-compilado-dist
          path: |
            dist/
            **/dist/
            build/
            **/build/
